name: Kitty Deploy

on:
  push:
    branches:
      - master
  
  workflow_dispatch:

  repository_dispatch:
    types: [workflow]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
      - name: Use Python
        uses: actions/setup-python@v2
      - name: "Deploy" 
        run: |
          pip install fandogh_cli --upgrade
          COLLECT_ERROR=True fandogh login --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}
          fandogh namespace active --name mjavad
          fandogh image publish --version ${{ steps.generate-uuid.outputs.uuid }}
          fandogh service deploy --name warm-kitty --version  ${{ steps.generate-uuid.outputs.uuid }}