name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Deploy to Liara"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "20"
      - name: "Deploy"
        run: |
          npm i -g @liara/cli@2
          npm install typescript
          npm run build
          cd ./dist
          liara deploy --api-token="${{ secrets.LIARA_TOKEN }}" --region iran --detach